### ISSUE TITLE
Why using getStaticProps?

### ISSUE THREAD

**Issue by Katona** [Tonel/how-to-perform-ab-testing-nextjs#1]
The article and the example is misleading since `getStaticProps` which is used to decide which version to display to the user runs during build time and not during every request. This means if someone builds this page with `npm run build` then only one version of the landing page will be generated and will be served to every user until the page is rebuilt. The only reason it seems to be working in the example because Next.js runs `getStaticProps` on every request during development.

How to reproduce the issue:

1. Run `npm run build`.
2. Launch the app built previously by running `npm start`.
3. Observe that always the same variant is served by reloading the page several times.

**Comment by Tonel** [comment]
Hey, thanks for pointing out that. However, that is not true.
The `revalidate: 60` parameter in `getStaticProps` activates the Next.js [Incremental Static Regeneration](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration) feature, which ensures that the page is regenerated after 60 seconds. So, the A/B testing logic should work as expected.

**Comment by Katona** [comment]
You are right, I missed that. However, this can now result in serving _different_ versions of the page to the same user in the same session (like navigation away and back, or any user action triggering a page reload). Also, having a rebuilding the page in every minutes almost defeats the purpose of pre-generation in my opinion.

**Comment by Katona** [comment]
Placing the decision logic into `getStaticProps` is a mistake and if you want to build an A/B testing solution for _real life_ you will end up moving that to elsewhere, like a [middleware](https://vercel.com/guides/ab-testing-on-vercel).

**Comment by Tonel** [comment]
Next.js middleware becomes with version `12.2`, released after that article was published. What I explained in the article is a working way to implement A/B testing in Next.js, but there might be several other approaches. 

Saying "is a mistake" without explaining why is not useful, so please provide more details.

**Comment by Katona** [comment]
Let me quote myself:
> However, this can now result in serving different versions of the page to the same user in the same session (like navigation away and back, or any user action triggering a page reload).

So if a user reloads the page while it was rebuilt due to invalidation he/she will get a different version which is a bad UX and probably can screw up analytics as well. To prevent this, you need to keep track which variant is served to a user, potentially with cookies, therefore:
- you either drop static generation, since there is no cookie during build time.
- or you use middlewares.
